### ISSUE TITLE
com.google.gson.internal.LinkedTreeMap cannot be cast to org.bukkit.Location

### ISSUE THREAD

**Issue by lennoox** [EinTestNetzwerk/EineMapAPI#1]
Help me

Save New Duplicate & Edit Just Text Twitter
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
rg.bukkit.event.EventException
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot.jar:git-Spigot-de459a2-51263e9]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot.jar:git-Spigot-de459a2-51263e9]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot.jar:git-Spigot-de459a2-51263e9]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot.jar:git-Spigot-de459a2-51263e9]
	at net.minecraft.server.v1_10_R1.PlayerList.onPlayerJoin(PlayerList.java:333) [spigot.jar:git-Spigot-de459a2-51263e9]
	at net.minecraft.server.v1_10_R1.PlayerList.a(PlayerList.java:159) [spigot.jar:git-Spigot-de459a2-51263e9]
	at net.minecraft.server.v1_10_R1.LoginListener.b(LoginListener.java:144) [spigot.jar:git-Spigot-de459a2-51263e9]
	at net.minecraft.server.v1_10_R1.LoginListener.E_(LoginListener.java:54) [spigot.jar:git-Spigot-de459a2-51263e9]
	at net.minecraft.server.v1_10_R1.NetworkManager.a(NetworkManager.java:233) [spigot.jar:git-Spigot-de459a2-51263e9]
	at net.minecraft.server.v1_10_R1.ServerConnection.c(ServerConnection.java:140) [spigot.jar:git-Spigot-de459a2-51263e9]
	at net.minecraft.server.v1_10_R1.MinecraftServer.D(MinecraftServer.java:827) [spigot.jar:git-Spigot-de459a2-51263e9]
	at net.minecraft.server.v1_10_R1.DedicatedServer.D(DedicatedServer.java:400) [spigot.jar:git-Spigot-de459a2-51263e9]
	at net.minecraft.server.v1_10_R1.MinecraftServer.C(MinecraftServer.java:668) [spigot.jar:git-Spigot-de459a2-51263e9]
	at net.minecraft.server.v1_10_R1.MinecraftServer.run(MinecraftServer.java:567) [spigot.jar:git-Spigot-de459a2-51263e9]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_131]
Caused by: java.lang.ClassCastException: com.google.gson.internal.LinkedTreeMap cannot be cast to org.bukkit.Location
	at de.lennox.core.game.map.MapAPI.teleportPlayer(MapAPI.java:110) ~[?:?]
	at net.diice.jumpduell.listener.PlayerListener.onJoin(PlayerListener.java:50) ~[?:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_131]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_131]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_131]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_131]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[spigot.jar:git-Spigot-de459a2-51263e9]
	... 14 more

**Comment by PascalKu** [comment]
Hey lennoox,

vielen Dank, dass du uns diesen schwerwiegenden Fehler gemeldet hast. Wir arbeiten an diesem Rückumwandlungsfehler.

Um die Nutzung dennoch zu gewähren haben wir eine temporäre Methode getLocation() eingefügt, welche vorübergehend in der API ist.

Beispiel zur Nutzung:

> Location location = EineMapAPI.getLocation((LinkedTreeMap) map.getObjectMap().get("tuhle_location"));

Um dieses Update zu erhalten musst du natürlich die Maven-Datei aktualisieren.

Sollte es weitere Fehler geben erstelle bitte einfach ein neues Ticket.
